version: '3'
services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=valid_create_update_service
volumes:
  db-data:
